### ISSUE TITLE
[Report Bug]: Valid emails are not being taken up in the Registration screen

### ISSUE THREAD

**Issue by IamRaja007** [vigneshshettyin/Meetly#16]
### Description

While registering an user in the Registration screen ( RegisterActivity ), if an user adds a white-space after the email by mistake, then the email address is deemed to be invalid, though it is not.
We should check for any white-spaces appended with the texts in the field inputs. We can maybe trim the strings from the end to fix this bug.

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by IamRaja007** [comment]
@vigneshshettyin I want to work on this issue. Please assign it to me.

**Comment by vigneshshettyin** [comment]
Hey, @IamRaja007 assigning this issue to you.
