### ISSUE TITLE
[Feature Request]: Hiding of keyboard after pressing Login Button, Register Button, and Reset Password Button in Auth section

### ISSUE THREAD

**Issue by its-me-debk007** [vigneshshettyin/Meetly#18]
### Description

Description

After filling the fields in the auth section, we must hide the keyboard for a better user experience. In case, if the user does not closes the keyboard manually, he/she will not able to see the snackbar in case of any error.

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by its-me-debk007** [comment]
@vigneshshettyin Sir, Please assign this issue to me under GSSOC. I'll be glad to work on this issue and help improve the app using my insights as well.

**Comment by vigneshshettyin** [comment]
Hey, @its-me-debk007 assigning this issue to you.
