### ISSUE TITLE
[Feature Request]: A section where it displays information about all the libraries used in meetly app

### ISSUE THREAD

**Issue by priyanshuborole** [vigneshshettyin/Meetly#21]
### Description

**Description**
Will create a new activity where it displays information about all the libraries used in the meetly app. For now, will add information about 2 libraries so later others can also contribute to the remaining libraries

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshuborole** [comment]
Hello @vigneshshettyin can I work on this feature request?

**Comment by vigneshshettyin** [comment]
Hey, @priyanshuborole assigning this issue to you. Please follow the colour scheme of the app also the dark/light mode colour scheme while you contribute.

**Comment by priyanshuborole** [comment]
Ok sure @vigneshshettyin

**Comment by vigneshshettyin** [comment]
Closing (https://github.com/vigneshshettyin/Meetly/pull/26)
