### ISSUE TITLE
[Feature Request]: Gradient in Status Bar and Toolbar

### ISSUE THREAD

**Issue by its-me-debk007** [vigneshshettyin/Meetly#22]
### Description

Description
We can apply gradient in the toolbar and status bar instead of a single color., which looks more appealing to the eyes. May suggest a better gradient.

![msg876029335-6134](https://user-images.githubusercontent.com/81604986/156904218-da90a5f2-fd12-4d9d-b682-4fc410b5dbf9.jpg)
![msg876029335-6135](https://user-images.githubusercontent.com/81604986/156904214-cce7c280-ef27-426a-810b-f2b663b22896.jpg)

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by its-me-debk007** [comment]
Please assign this to me under GSSOC, I wanna work on this.

**Comment by vigneshshettyin** [comment]
Cool, you can work on it. @its-me-debk007. Also, it would be great if you could raise an issue for changing side navigation to bottom navigation if you interested

**Comment by its-me-debk007** [comment]
Thanks for assigning me this issue @vigneshshettyin!

And I would love to work on the new issue. Can you please specify which options I should include in the bottom navigation view

**Comment by vigneshshettyin** [comment]
Yes, one is to create a new meeting, then next remove the bottom right filter button and add it there, then profile view, next settings where all the remaining options of the sidebar should show up. You first suggest a UI for it then let's go forward! @its-me-debk007

**Comment by its-me-debk007** [comment]
Hi @vigneshshettyin. We can use:

![image](https://user-images.githubusercontent.com/81604986/161226847-31a5ac80-7d0a-4f47-8ba4-a1b311fac92f.png)

OR

![image](https://user-images.githubusercontent.com/81604986/161228734-d0140d33-ef7c-4a56-8e78-5ff8362d383c.png)

You can click here to see the gif of the above image
https://kodular-community.s3.dualstack.eu-west-1.amazonaws.com/original/3X/3/f/3f3fa5993bed34c84f7d20709450284d9cdb4fe5.gif

**Comment by vigneshshettyin** [comment]
Hey, @its-me-debk007 second one is good. You can go ahead and implement that. Please remove the sidebar after implementing the bottom navigation also match the colour scheme.

**Comment by its-me-debk007** [comment]
Okay @vigneshshettyin! I have raised an issue for the Bottom Navigation View

**Comment by its-me-debk007** [comment]
I have implemented gradient in 4 ways. Which one looks better?

![msg876029335-6818](https://user-images.githubusercontent.com/81604986/161257165-1d01e0e9-3f24-471a-9ab9-424d6c95f8c9.jpg)

![msg876029335-6819](https://user-images.githubusercontent.com/81604986/161257193-0f78f58c-3e81-4427-8be2-efa0475d61ce.jpg)

![msg876029335-6816](https://user-images.githubusercontent.com/81604986/161257215-a14f4196-d3d0-4a0a-8779-05b851a2fcaa.jpg)

![msg876029335-6817](https://user-images.githubusercontent.com/81604986/161257228-cbe081a3-9240-41d9-ba2c-df4510b8eaf6.jpg)

**Comment by vigneshshettyin** [comment]
Last one looks dope ig @its-me-debk007
