### ISSUE TITLE
[Report Bug]: "Logged in!" toast pops up everytime user opens the app if previously signed in.

### ISSUE THREAD

**Issue by its-me-debk007** [vigneshshettyin/Meetly#23]
### Description

Description

Every time user open the app, a toast pops up which says "Logged in!" if previously logged in, which is only required when user logs in. 

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by its-me-debk007** [comment]
Please assign this to me, I want to work on this.

**Comment by vigneshshettyin** [comment]
Hey, @its-me-debk007 assigning this issue to you!
