### ISSUE TITLE
[Feature Request]: Individual helper text for each TextInputLayout in Auth, to help user better understand the error/validation

### ISSUE THREAD

**Issue by its-me-debk007** [vigneshshettyin/Meetly#24]
### Description

Description

Individual helper texts must be added for each input field to help user better understand a specific error/validation. This provides an improved user-experience. 

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Please allow me to work on this issue**

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue.

**Comment by vigneshshettyin** [comment]
Hey, @AgarwalsRahul assigning this issue to you.

**Comment by AgarwalsRahul** [comment]
@vigneshshettyin what type of helper text is needed? Do we have to show the errors below the textfields?

**Comment by vigneshshettyin** [comment]
Yes @AgarwalsRahul

**Comment by AgarwalsRahul** [comment]
Okay

**Comment by AgarwalsRahul** [comment]
@vigneshshettyin is it fine?
![Screenshot_20220406-133704](https://user-images.githubusercontent.com/63352614/161927238-cb8b7e81-9ae2-4eeb-9e7c-59b58ace44f6.png)

**Comment by vigneshshettyin** [comment]
Yes @AgarwalsRahul
