### ISSUE TITLE
[Feature Request]: An improved exit confirmation dialog with lottie animation

### ISSUE THREAD

**Issue by its-me-debk007** [vigneshshettyin/Meetly#25]
### Description

Description

Whenever user tries to exit the app, the exit confirmation dialog must be visually appealing with a proper icon and a beautiful animation on the dialog!

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by its-me-debk007** [comment]
Please allow me to work on this issue

**Comment by vigneshshettyin** [comment]
Hey, @its-me-debk007 assigning this issue to you!

**Comment by its-me-debk007** [comment]
@vigneshshettyin , is it ok?

https://user-images.githubusercontent.com/81604986/161194322-328cce8b-2981-4f29-a952-c9432f8ff6de.mp4

**Comment by vigneshshettyin** [comment]
Hey, @its-me-debk007 yes, but would you try with some other font.

**Comment by its-me-debk007** [comment]
Change the font, and applied curves
How does it look now, @vigneshshettyin 

https://user-images.githubusercontent.com/81604986/161217604-f45b0711-da92-4aa4-ba8a-de7e4a4dd441.mp4

**Comment by its-me-debk007** [comment]
Update: 
Decreased font size of heading and increased curve radius

![msg876029335-6814](https://user-images.githubusercontent.com/81604986/161225810-3820f2d1-408b-46a3-b9a6-57ac7fabf54f.jpg)

**Comment by vigneshshettyin** [comment]
Yup, this is fine @its-me-debk007
