### ISSUE TITLE
[Feature Request]: Modify the team activity in the app.

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Meetly#27]
### Description

The current team section in the app has static content it must be removed and replaced with all the contributors working on this project (ie Meetly). All contributors' data will be fed using the API.

Library to be used for making API calls Retrofit

API: https://githubcapi.herokuapp.com/get-meetly-data/

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by aayushpathak11** [comment]
I would like to work on this issue.
I have an approach in mind of using recycler view and feeding it data through api.

**Comment by aayushpathak11** [comment]
@vigneshshettyin I would like to work on this issue.
I have an approach in mind of using recycler view and feeding it data through api.

**Comment by vigneshshettyin** [comment]
Cool, assigning this issue to you. Please share ur UI design before you start.

**Comment by vigneshshettyin** [comment]
> Cool, assigning this issue to you. Please share ur UI design before you start.

@aayushpathak11

**Comment by aayushpathak11** [comment]
![image](https://user-images.githubusercontent.com/77546902/157188366-bf98674f-aec8-4f16-8515-61ca7e7bca2b.png)
@vigneshshettyin I am thinking Individual items of list should look like this as no linkedin or gmail url is in api.
Also Textview "Android Developer" is still static , should i include username field of API in place of it?
[I think username will not be very appealing from UI point of view].

Suggestions Please.

**Comment by vigneshshettyin** [comment]
Hey, the current one looks great one small suggestion try to add two blocks in a row. @aayushpathak11

**Comment by vigneshshettyin** [comment]
Remove 'Android Developer' @aayushpathak11 as GitHub link will anyway redirect to their GitHub profile username is not required ig

**Comment by vigneshshettyin** [comment]
![Screenshot_20220308-132417_Chrome.jpg](https://user-images.githubusercontent.com/77713888/157191688-54002f1e-3bae-41bd-b01a-426f8cb7d5bf.jpg)

Ig this kind of look may look good could you try to implement this it's simple and clean.

@aayushpathak11

**Comment by aayushpathak11** [comment]
![image](https://user-images.githubusercontent.com/77546902/157199440-5b4fcb50-594a-45e9-9ad5-387d05f7cf58.png)
@vigneshshettyin Design looks like this , matches with App's theme and on clicking the tile of the person , user will be directed to github url.
Is this good? Can I move ahead with implementation part?

**Comment by vigneshshettyin** [comment]
> ![image](https://user-images.githubusercontent.com/77546902/157199440-5b4fcb50-594a-45e9-9ad5-387d05f7cf58.png)
> @vigneshshettyin Design looks like this , matches with App's theme and on clicking the tile of the person , user will be directed to github url.
> Is this good? Can I move ahead with implementation part?

Yeah @aayushpathak11, go ahead!
