### ISSUE TITLE
[Feature Request]: Shimmer Frame Layout for RecyclerViews

### ISSUE THREAD

**Issue by aayushpathak11** [vigneshshettyin/Meetly#29]
### Description

Whenever a Recycler View is loading from some API/Database , there may be a gap in between for loading time, I suggest that gap could be filled by shimmer effect so that it looks nice from user experience perspective.

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by aayushpathak11** [comment]
Hi @vigneshshettyin ,
I would like to work upon this issue.

**Comment by vigneshshettyin** [comment]
Hey, @aayushpathak11 assigning this issue to you.

**Comment by aayushpathak11** [comment]
Hello @vigneshshettyin sir, sorry for the delay in work. It was due to some college commitments.

I have **added Shimmer Layout** in both Support Activity and Main Activity but I have a few doubts before making the PR.

Doubt 1) When I click on the Support Updates in the app, **it shows me a blank screen**. Recycler view is activated (as shimmer layout disappears) but nothing appears on the screen. I am attaching the screenshot of how it appears to me.

![WhatsApp Image 2022-03-31 at 12 05 10 AM](https://user-images.githubusercontent.com/77546902/160906964-ee6921fc-5efe-4d6f-a472-06119c61144b.jpeg)

Doubt 2) There is already a preloader in the app which does exactly the same thing of filling up the time while recyclerview is loading , So now as I have added shimmer layout they should be removed.
 
Doubt 3) There are more activities where recyclerview is present. Should I apply shimmer layout in all of them?

**Comment by vigneshshettyin** [comment]
Hey, @aayushpathak11 thanks for responding. Support updates are loaded from the firestorm.  As there are not any entries present so, the data won't display there. The current preloader is present pls remove it from the codebase. Yes, add a shimmer layout to all the activities. Hope I have answered all your questions.
