### ISSUE TITLE
[Report Bug]: If not allowed permission at starting, then the app does not open.

### ISSUE THREAD

**Issue by its-me-debk007** [vigneshshettyin/Meetly#30]
### Description

If user refuses to allow permission at starting, then the app just pauses at the splash screen, and no further page opens. 

Please assign me this issue under GSSOC 2022.

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vigneshshettyin** [comment]
Yes, assigning this issue to you!

**Comment by its-me-debk007** [comment]
Hey @vigneshshettyin! If user denies the permission, should the user be prompt to give the permission or should the user be allowed to use the app and ask permission when needed?

**Comment by vigneshshettyin** [comment]
Provide a prompt to give permission.

**Comment by vigneshshettyin** [comment]
> Provide a prompt to give permission. 

@its-me-debk007
