### ISSUE TITLE
[Feature Request]: Implementing Bottom Navigation View 

### ISSUE THREAD

**Issue by its-me-debk007** [vigneshshettyin/Meetly#33]
### Description

We can implement Chip Navigation Bar which is shown as follows

![image](https://user-images.githubusercontent.com/81604986/161228734-d0140d33-ef7c-4a56-8e78-5ff8362d383c.png)

Here is the GIF for the nav bar
https://kodular-community.s3.dualstack.eu-west-1.amazonaws.com/original/3X/3/f/3f3fa5993bed34c84f7d20709450284d9cdb4fe5.gif

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by its-me-debk007** [comment]
Please assign me this

**Comment by vigneshshettyin** [comment]
Hey, @its-me-debk007 any progress?

**Comment by its-me-debk007** [comment]
Almost done! Will show the implementation tonight

**Comment by vigneshshettyin** [comment]
Great! @its-me-debk007

**Comment by its-me-debk007** [comment]
Sorry for the delay! Here is the implementation
https://user-images.githubusercontent.com/81604986/161854655-1d396e3a-0730-4455-9664-1206528dd051.mp4

**Comment by vigneshshettyin** [comment]
Hey, the settings activity is looking very bad I would suggest you check for some designs from dribble and implement them. you can raise a different issue for this. A dark/light mode switch button in the settings section would be great! @its-me-debk007

**Comment by its-me-debk007** [comment]
Is it fine @vigneshshettyin ? Will also put dark/light mode in the options
![image](https://user-images.githubusercontent.com/81604986/162003587-20355437-ff94-4401-9aac-b4cca2cb3e22.png)

**Comment by vigneshshettyin** [comment]
Yes, works @its-me-debk007

**Comment by vigneshshettyin** [comment]
Hey, @its-me-debk007 np

**Comment by its-me-debk007** [comment]
Thanx @vigneshshettyin!!
