### ISSUE TITLE
[Feature Request]: An Onboarding Screen Experience for users using the app for the very first time

### ISSUE THREAD

**Issue by aayushpathak11** [vigneshshettyin/Meetly#38]
### Description

- An Onboarding screen should be implemented in the app for the users using the app for the very first time.
- User will get to know what to expect from the app and how to use the app more effectively.
- All the best practices and necessary information of the app could be displayed to the user in a user-friendly way.
- EXAMPLE OF AN **ONBOARDING SCREEN** - 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/77546902/161381812-0121d24a-fda5-4ecf-945c-eb6eaf59671c.gif)

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by aayushpathak11** [comment]
@vigneshshettyin sir
- Should this idea be implemented?
- Does Meetly need this?
If yes, I would like to work on this.

**Comment by vigneshshettyin** [comment]
Hey, @aayushpathak11 great idea you can proceed with this idea

**Comment by chazuttu** [comment]
@aayushpathak11 Any Updates?

**Comment by aayushpathak11** [comment]
Yes , working on it.

**Comment by TG922** [comment]
Hey there Is someone working on this issue??

**Comment by vigneshshettyin** [comment]
@aayushpathak11 are you working on it ??

**Comment by chazuttu** [comment]
Anyone working on it or should we close it?
@vigneshshettyin Sir, Should we close it??
