### ISSUE TITLE
[Feature Request]: Create a Static Page for Privacy Policy using React

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Meetly#46]
### Description

Description: Redesign of Privacy Policy page using React JS

Branch : gh-pages
Live URL : https://vigneshshettyin.github.io/Meetly/

### Domain

Static Page (React)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by godspeed-03** [comment]
Hii @vigneshshettyin , I would like to work on this issue. I wanted to know about the concept of UI which has to be implemented on the Privacy Policy Page.
