### ISSUE TITLE
[Feature Request]: Add the pr-title-checker.yml and it's json for keeping tracks of PR.

### ISSUE THREAD

**Issue by praptisharma28** [vigneshshettyin/Meetly#51]
### Description

Description
This will :
/Improved Code Organization: Consistent PR titles will enhance code organization and searchability.
/Streamlined Workflow: Integration with CodeQL and a dedicated workflow will promote efficiency and automation.
/Reduced Manual Effort: Automated checks will minimize the need for manual title review, freeing up time for development tasks.

### Domain

Documentation

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by praptisharma28** [comment]
Assign me @vigneshshettyin here under iwoc

**Comment by vigneshshettyin** [comment]
Assigned @praptisharma28
